### ISSUE TITLE
Training and Inference Time/FPS

### ISSUE THREAD

**Issue by DiamondGlassDrill** [Bin-ze/sfm-free-gaussian-splatting#2]
@Bin-ze thanks for the impressive work, do you have a comparison of training time and inference speed for e.g. retail consumer GPUs like 3090 or 4090ti?
How does your sfm-free-GS compares to GLOMAP in performance speed/quality, maybe you had time to try it? https://github.com/colmap/glomap

Thanks in advance.

**Comment by Bin-ze** [comment]
This algorithm focuses on constructing the Gaussian splatting scene. Although the colmap step is omitted, the incremental reconstruction of the gaussian scene takes a lot of time. Therefore, there is no speed advantage.
